Bug 1813449 - Fix accessibility issues on Tabs Tray screen
mozilla-mobile/firefox-android pull request #1007
Opened 2023-02-27 12:17 UTC by gitstart

### Description

See the screenshot below with numbered label (left emulator is of the issue, and right is of the fix) for accessibility issues.

<img width-="300" src="https://user-images.githubusercontent.com/13991373/221226853-112b1b3f-040f-4c9a-9724-f99ad40691a6.png">

Table below contains detail of the fixes applied.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/13991373/221226574-42e3c63a-3125-43cf-aba5-abc10c9292f6.png">

PS: No new test cases have been added

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

2023-02-27 13:17 UTC, Mugurell reviewed
The `contentDescription` for `handle` seems like a sensible change that we can take.
Previously Talkback would read "Unlabeled, Out of list. Double tap to activate".
Now it will read "Collapse. Out of list. Double tap to activate"

2023-02-27 13:17 UTC, Mugurell commented on fenix/app/src/main/res/values-night/colors.xml
> +    <color name="fx_mobile_action_color_primary">@color/photonViolet50</color>
App resources - colors / strings etc should not be changed without first confirming with UX.
Given the importance of this particular two colors - used in many places all throughout the app I suggest dropping the color changes to unlock landing other parts of the PR.

2023-02-27 13:18 UTC, Mugurell requested changes
r- for the color changes.
If those are dropped we can land the `contentDescription` update for `handle`.

2023-03-01 12:52 UTC, gitstart commented
> r- for the color changes. If those are dropped we can land the `contentDescription` update for `handle`.

Hello @Mugurell,🙏
Requested changes pushed.🚀

2023-03-01 13:30 UTC, Mugurell approved these changes
LGTM. Thank you!

2023-03-01 13:35 UTC, merged