Bug 1814192 - Hide the delete menu item when there is no browsing data
mozilla-mobile/firefox-android pull request #1050
Opened 2023-03-01 12:31 UTC by gitstart

### What
The PR will hide the delete menu item when there is no browsing data

### Screenshots
| Issue video | Fix Video |
| ----------- | --------- |
|  https://user-images.githubusercontent.com/2725300/221115989-336e3206-794a-4988-8580-1c4a33b7ad2d.mp4 | https://user-images.githubusercontent.com/2725300/221485161-ee43f2b0-9be2-49d2-a96b-38dc5df392c8.mp4 |

### Pull Request checklist
 - [X] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.
### GitHub Automation

2023-03-01 16:08 UTC, t-p-white commented
@gitstart thank you for your contribution! I would like to get some UX input on this, as the solution is ambiguous (disabled or removed)

@mozilla-mobile/ux do we want the button to be disabled or removed?

2023-03-01 20:54 UTC, lime124 commented
Hi! Thanks for your contribution! I agree it doesn't make sense to allow people to delete their history when there is no history to delete. 

Instead of hiding the button, the trash can should remain visible but instead be in the inactive state. Can you make that change please? Thanks!

2023-03-02 06:16 UTC, gitstart commented
> Hi! Thanks for your contribution! I agree it doesn't make sense to allow people to delete their history when there is no history to delete.
> 
> Instead of hiding the button, the trash can should remain visible but instead be in the inactive state. Can you make that change please? Thanks!

@lime124 Should the inactive button have a different colour from the active button? If so which colour should it have? Thank you for getting back to me so quickly.

2023-03-03 18:56 UTC, Piratesarereal commented
inactive/disabled state colour

For dark mode - rgba(251, 251, 254, 0.4);
For light mode - rgba(21, 20, 26, 0.4);

Users should not be able to interact with the icon button.

2023-03-09 22:06 UTC, amedyne commented
@t-p-white when you have time to re-review this, this is good to go per review with UX and product.

2023-03-20 12:05 UTC, t-p-white commented on fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
> +    private fun updateDeleteMenuItemView(isEmpty: Boolean) {
nit: can we update 'isEmpty' to something like 'enabled' or ''isEnabled' then update callers as required

2023-03-20 12:07 UTC, t-p-white requested changes
Thanks again for your contribution! This is looking good 👍 once the comment is addressed, this is good to go

2023-03-28 16:33 UTC, t-p-white requested changes
Thank you for quickly addressing the previous comment. Apologies, I may not have been clear, but can you also update the callers to inverse the logic please? Essentially so the code reads as "disable the delete menu item if there is no history". The suggestions I've added will do that

2023-03-28 16:33 UTC, t-p-white commented on fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
> +            updateDeleteMenuItemView(it.isEmpty)
```suggestion
            updateDeleteMenuItemView(!it.isEmpty)
```

2023-03-28 16:33 UTC, t-p-white commented on fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
> +        if (isEnabled) {
```suggestion
        if (!isEnabled) {
```

2023-03-28 16:33 UTC, t-p-white commented on fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
> +            updateDeleteMenuItemView(historyStore.state.isEmpty)
```suggestion
            updateDeleteMenuItemView(!historyStore.state.isEmpty)
```

2023-04-02 03:25 UTC, gitstart commented
> 

Thank you @t-p-white for reviewing🙏.
Requested changes are pushed. 🚀

2023-04-05 12:19 UTC, t-p-white commented
@gitstart no problem! This is great, thank you. Can you squash these 10 commits to a single commit please, and we can get this landed 🙏

2023-04-07 06:40 UTC, gitstart commented
> @gitstart no problem! This is great, thank you. Can you squash these 10 commits to a single commit please, and we can get this landed 🙏

Hello @t-p-white,
Squashed commit pushed. Please take a look..

2023-04-13 03:25 UTC, t-p-white approved these changes
Thank you for your contribution @gitstart, nice work.

2023-04-13 03:54 UTC, merged