Bug 1812730 - Prevent collections with empty name from being created
mozilla-mobile/firefox-android pull request #1356
Opened 2023-03-22 06:06 UTC by gitstart

### What
The PR will disable the dialog `OK` button and keyboard `DONE` button if the collection name is `blank`

### Steps to test
### Method 1

1. Open a tab with a web page open
2. Click on `three dot menu`
3. Select `Save to collection`
4. Delete the default name
5. Try saving by clicking on the keyboard `Done` button
6. Repeat steps `1 - 3`  
7. Enter a name with spaces at the beginning and end 

### Method 2
1. Make sure you have more than 1 tab open with a web page open
2. Click on the tab tray
3. Click on `three dot menu`
4. Click on `Select tabs`
5. Select one or more tabs
6. Click on `Collection button`
7. Click on ~Add new collection`
8. Delete the name and try saving or
9. Append and prepend spaces on the name 

### Screenshots
| Issue video | Fix Video |
| ----------- | --------- |
| https://www.loom.com/share/6880e832f260420ab3a26a5a88045420 | https://www.loom.com/share/5155001bee58479c91856252c611affe|

### Pull Request checklist
 - [X] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### GitHub Automation

2023-08-07 10:58 UTC, titooan requested changes
Great job, looks good to me! 

I only suggested a small code improvment, and after the code is rebased it shoud be ready to merge.

Thanks for this contribution!

2023-08-07 10:58 UTC, titooan commented on fenix/app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt
> +    )
You can use the [TextView.doOnTextChanged](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/core/core-ktx/src/main/java/androidx/core/widget/TextView.kt#42) extension function to make the code cleaner. 

```suggestion
    collectionNameEditText.doOnTextChanged { text, _, _, _ ->
        dialog.getButton(DialogInterface.BUTTON_POSITIVE).isClickable = text.toString().isNotBlank()
    }
```

2023-08-10 05:03 UTC, gitstart commented
Hi @titooan Thanks for reviewing PR. Requested changes has been pushed. Can you please re-review?

2023-08-28 18:27 UTC, titooan commented
Sorry for the delay, and thanks for applying the changes! It looks good to me.

2023-08-28 18:27 UTC, titooan commented
bors try

2023-08-28 19:48 UTC, titooan commented
bors try

2023-08-28 21:04 UTC, titooan approved these changes

2023-08-28 21:06 UTC, merged