Bug 1823929 - new ETP tests
mozilla-mobile/firefox-android pull request #1362
Opened 2023-03-22 14:46 UTC by sv-ohorvath

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2023-03-23 14:16 UTC, AndiAJ approved these changes
👍🏽

2023-03-23 16:47 UTC, AaronMT requested changes
Looks like a minor conflict, otherwise looks OK to me. Lot of refactoring here.

2023-03-23 16:47 UTC, AaronMT commented on fenix/app/src/androidTest/assets/pages/trackingPage.html
> +   - test page. -->
Mind also adding source repository https://github.com/mozilla/anti-tracking-test-pages

2023-03-24 10:09 UTC, sv-ohorvath commented on fenix/app/src/androidTest/assets/pages/trackingPage.html
> +   - test page. -->
done

2023-03-24 10:54 UTC, merged