Bug 1821210 -  Added content description on Back button to say `Navigate up button`
mozilla-mobile/firefox-android pull request #1513
Opened 2023-04-02 03:33 UTC by gitstart

### What
Back button when clicked doesn't say "Navigate up button"

### Screenshots
### Issue video

https://user-images.githubusercontent.com/39338964/224269698-de088e2b-5f18-4127-b77f-c51fbb5dcbfc.mp4

### Demo video after fix

https://user-images.githubusercontent.com/39338964/224269904-b809f89a-5215-46cc-ba68-8d195917b766.mp4

### Pull Request checklist
 - [x] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [x] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### GitHub Automation
Used by GitHub Actions.

2023-06-14 11:06 UTC, t-p-white commented
bors try

2023-06-15 10:07 UTC, t-p-white commented on android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BackPressMenuItem.kt
> +        view.contentDescription =  contentDescription
```suggestion
        view.contentDescription = contentDescription
```

2023-06-15 10:10 UTC, t-p-white requested changes
Please see comment 🙂

2023-06-21 05:32 UTC, gitstart commented
Thank you @t-p-white for reviewing our PR. 
We pushed the changes requested. ✔

2023-06-21 09:20 UTC, t-p-white commented
bors try

2023-06-22 16:13 UTC, t-p-white commented
bors try

2023-06-23 13:33 UTC, t-p-white commented
bors try

2023-06-26 09:52 UTC, t-p-white commented
bors try

2023-06-26 11:43 UTC, t-p-white approved these changes
@gitstart thank you for your contribution, nice work 👍

2023-06-26 12:07 UTC, merged