Bug 1802010 - After adding a shortcut, show a confirmation message
mozilla-mobile/firefox-android pull request #1600
Opened 2023-04-10 07:58 UTC by gitstart

### What
Show a snack bar when a website is added to shortcut

### Issue video
[fnx-62-issue.webm](https://user-images.githubusercontent.com/35276272/224277226-f77b37ad-81da-4663-a1d6-26f5f4a86f0c.webm)

### Demo video after fix
[fnx-62-fix.webm](https://user-images.githubusercontent.com/35276272/224272629-29ae582d-9b3e-4cc2-9e0c-5bab7d1f3538.webm)

### Pull Request checklist
 - [x] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [x] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### GitHub Automation
Used by GitHub Actions.

2023-05-16 22:23 UTC, MatthewTighe requested changes
Couple small things, but this is otherwise looking good! Thanks for the contribution!

2023-05-16 22:23 UTC, MatthewTighe commented on focus-android/app/src/main/res/values/strings.xml
> +    <string name="added_to_shortcut">Added to shortcuts</string>
Let's update this string's ID and it's content to match Fenix:

`<string name="snackbar_added_to_shortcuts">Added to shortcuts!</string>`

2023-05-16 22:23 UTC, MatthewTighe commented on focus-android/app/src/main/res/values/strings.xml
> +    <!-- Snackbar that will be displayed after a website has been added to shortcut. -->
nit:
```suggestion
    <!-- Snackbar that will be displayed after a website has been added to shortcuts. -->
```

2023-05-24 17:23 UTC, MatthewTighe requested changes

2023-05-24 17:23 UTC, MatthewTighe commented on focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
> +            .setText(requireContext().getString(R.string.added_to_shortcut))
I think we will hit a compile error unless this resource ID is updated

2023-06-05 19:27 UTC, debojyoti452 commented
Hello @MatthewTighe,
Requested changes are pushed. ✔

2023-06-05 20:23 UTC, MatthewTighe approved these changes
LGTM! Thanks for your contribution!

2023-06-05 20:23 UTC, MatthewTighe commented
bors try

2023-06-05 22:41 UTC, MatthewTighe commented
bors retry

2023-06-06 00:27 UTC, merged