Bug 1836896 - Hide statusbar when fullscreen on Android R+ devices
mozilla-mobile/firefox-android pull request #2844
Opened 2023-07-14 02:06 UTC by jackyzy823

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2023-08-07 12:36 UTC, t-p-white requested changes
Nice solution, works well 👍 could you also update the tests in ActivityTest please? See example of testing with SDK [version here](https://github.com/mozilla-mobile/firefox-android/blob/e0f85f8a669b676847e890235d4bdfa7840d7f2c/android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/view/MenuViewTest.kt#L64)

2023-08-07 15:04 UTC, t-p-white commented
bors try

2023-08-07 17:10 UTC, jackyzy823 commented
Not very sure the test sufficient or not.

2023-08-08 07:56 UTC, t-p-white commented
@jackyzy823 thank you so much for adding the tests! Wdyt about updating & duplicating the existing tests for enter and exit with the Android version? e.g:

-  `check setAsImmersive sets the correct flags`
-  `check exitImmersiveMode sets the correct flags`

becomes:

-  `check setAsImmersive sets the correct flags for Android R and above`
-  `check setAsImmersive sets the correct flags for Android below R`
-  `check exitImmersiveMode sets the correct flags for Android R and above`
-  `check exitImmersiveMode sets the correct flags for Android below R`

2023-08-08 13:12 UTC, jackyzy823 commented
@t-p-white I tried to do this ,but due to i'm not familiar with mocking.

doing so
```kotlin
    @Test
    @Config(sdk = [Build.VERSION_CODES.R])
    fun `check setAsImmersive sets the correct flags  on devices with Android R and above`() {
        `when`(window.getInsetsController()).thenReturn(windowInsetsController)

        activity.setAsImmersive()

        verify(decorView).systemUiVisibility = View.SYSTEM_UI_FLAG_FULLSCREEN
        verify(decorView).systemUiVisibility = View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
        verify(window.decorView, never()).setOnSystemUiVisibilityChangeListener(any())
        verify(window).setDecorFitsSystemWindows(false)
    }
```
will  cause
```kotlin
        verify(decorView).systemUiVisibility = View.SYSTEM_UI_FLAG_FULLSCREEN
        verify(decorView).systemUiVisibility = View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
```
not work.


It says
```
Wanted but not invoked:
view.setSystemUiVisibility(4);
-> at android.view.View.setSystemUiVisibility(View.java)
Actually, there were zero interactions with this mock.
```


If i don't mock with ``` `when`(window.getInsetsController()).thenReturn(windowInsetsController)``` , it argues ```java.lang.NullPointerException: Cannot invoke android.view.WindowInsetsController.hide(int) because  this.mInsetsController  is null
        at androidx.core.view.WindowInsetsControllerCompat$Impl30.hide(WindowInsetsControllerCompat.java:664)
        at androidx.core.view.WindowInsetsControllerCompat.hide(WindowInsetsControllerCompat.java:188)
        at mozilla.components.support.ktx.android.view.ActivityKt.setAsImmersive(Activity.kt:38)```

It would be helpful if you could figure out how to make this correct.

2023-08-09 12:58 UTC, t-p-white commented
@jackyzy823 thanks for looking into this, I see the same error. My solution is to leave the existing tests as-is (just updating the `Test` name to include the Android version part) and adding new tests for Android R - something similar too:

```
    @Test
    @Config(sdk = [Build.VERSION_CODES.R])
    fun `check setAsImmersive sets the correct flags on devices with Android R and above`() {
        `when`(window.insetsController).thenReturn(windowInsetsController)

        activity.setAsImmersive()

        verify(window).setDecorFitsSystemWindows(false)
        verify(windowInsetsController).hide(WindowInsetsCompat.Type.systemBars())
        verify(windowInsetsController).systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
    }
```

```
    @Test
    @Config(sdk = [Build.VERSION_CODES.R])
    fun `check exitImmersiveMode sets the correct flags on devices with Android R and above`() {
        `when`(window.insetsController).thenReturn(windowInsetsController)

        activity.exitImmersiveMode()

        verify(decorView).setOnApplyWindowInsetsListener(null)
        verify(window).setDecorFitsSystemWindows(true)
        verify(windowInsetsController).show(WindowInsetsCompat.Type.systemBars())
    }
```

Wdyt?

2023-08-09 14:39 UTC, jackyzy823 commented
@t-p-white thanks for advice.

2023-08-10 08:29 UTC, t-p-white commented on android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
> +    fun `check setAsImmersive sets the correct flags  on devices with Android Q and below`() {
```suggestion
    fun `check setAsImmersive sets the correct flags on devices with Android Q and below`() {
```

2023-08-10 08:29 UTC, t-p-white commented on android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
> +    fun `check setAsImmersive sets the correct flags  on devices with Android R and above`() {
```suggestion
    fun `check setAsImmersive sets the correct flags on devices with Android R and above`() {
```

2023-08-10 08:30 UTC, t-p-white commented on android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
> +        `when`(window.getInsetsController()).thenReturn(windowInsetsController)
```suggestion
        `when`(window.insetsController).thenReturn(windowInsetsController)
```

2023-08-10 08:30 UTC, t-p-white commented on android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
> +        `when`(window.getInsetsController()).thenReturn(windowInsetsController)
```suggestion
        `when`(window.insetsController).thenReturn(windowInsetsController)
```

2023-08-10 08:34 UTC, t-p-white commented on android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
> +        verify(windowInsetsController).systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
nit: my formatter is putting `WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE` on a newline

2023-08-10 08:38 UTC, t-p-white commented
@jackyzy823 np, thanks for adding the tests 🙂 if you could make the minor suggested changes, I think we're good to land. Thanks again for working on this bug, I'm sure the fix will be well received!

2023-08-10 13:54 UTC, t-p-white commented
bors try

2023-08-10 15:40 UTC, t-p-white commented
bors try

2023-08-10 15:52 UTC, t-p-white approved these changes

2023-08-11 08:26 UTC, t-p-white commented
bors try

2023-08-11 09:28 UTC, t-p-white commented
bors try

2023-08-11 11:54 UTC, t-p-white commented
bors try-

2023-08-11 11:54 UTC, t-p-white commented
bors try

2023-08-11 14:39 UTC, merged