Rvm androidx
mozilla-mobile/firefox-android pull request #3018
Opened 2023-07-27 22:08 UTC by rvandermeulen

2023-07-28 07:10 UTC, mcarare commented
Looks like we need to wait for ViewPager2's 1.1.0 release:

>Users of ViewPager2 must update to at least 1.1.0-beta02 when updating to this version of RecyclerView to avoid crashes.

2023-07-28 07:23 UTC, mcarare requested changes
either we add it as a direct dependency when released or wait for the fragment library to update the dependency in a future release.

2023-07-28 15:15 UTC, rvandermeulen commented
Blech, I overlooked that because we use that implicitly. I'll drop the Recyclerview update for now and spin that off to a new bug.

2023-07-31 06:16 UTC, mcarare approved these changes

2023-07-31 23:47 UTC, merged