Bug 1847247 - Make the password shortcut should take directly to the saved logins page
mozilla-mobile/firefox-android pull request #3443
Opened 2023-08-31 10:39 UTC by gitstart

### What
The PR makes the shortcut button on the Homepage to open the saved logins page.

### Steps to test

**Method 1**
1. Open the new shortcut "password shortcuts" by long pressing firefox icon,

### Screenshots
| Issue | Fix |
| ----- | --- |
|https://www.loom.com/share/e4cb450ff8634fc484312aac88eab51e | https://www.loom.com/share/d4bfbc6ef84f4fec8760892dc3521780?sid=5024e094-cc03-4776-80db-cf81c7c1f464 |

### Pull Request checklist
 - [x] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [x] Tests: This PR includes thorough tests or an explanation of why it does not
 - [x] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [x] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

2023-09-08 23:00 UTC, MatthewTighe commented
This looks good to me from a code perspective, but I am checking in with UX/product to see if we would prefer to navigate directly to this screen.

2023-09-11 21:53 UTC, MatthewTighe requested changes
Spoke with UX and had this flow approved. Would just like one comment added and then I'll cycle back for approval. Thanks for your contribution!

2023-09-11 21:53 UTC, MatthewTighe commented on fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
> +            verifyCredentialsOrShowSetupWarning(requireContext())
Could we add a comment here like:

// Handle auth and then navigate to saved logins

I think the `verifyCredentialsOrShowSetupWarning` could use a more clear name, but that's outside the scope of this patch.

2024-01-04 08:11 UTC, gitstart commented
Hi @MatthewTighe made requested changes, can you please review again?

2024-01-04 19:26 UTC, MatthewTighe commented
👋 hey there, thanks for revisiting this contribution! I am able to reproduce the failing unit test in `OpenPasswordManagerIntentProcessorTest`, so please get that fixed up before another review cycle 🙂

2024-04-03 07:06 UTC, gabrielluong commented
Hello, Thank you so much for your contribution. We have moved our firefox-android repo over to [mozilla-central](https://hg.mozilla.org/mozilla-central). Please feel free to reopen a new PR against the new repo. You will have to clone the new repository and reapply your changes. Thank you again, and sorry for the inconvenience.

For more information, please see https://github.com/mozilla-mobile/firefox-android/wiki#upcoming-migration-to-mozilla-central.

2024-04-03 07:06 UTC, closed without merging