Bug 1858193: Add a OneTimeWorkRequest to collect Telemetry for Installed Fonts
mozilla-mobile/firefox-android pull request #4140
Opened 2023-10-18 19:19 UTC by tomrittervg

I am going to work on a test for this code next, but wanted to put up a draft PR to get some initial feedback .

### Pull Request Checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2023-11-05 14:22 UTC, jonalmeida requested changes
This is a good first iteration! I left some comments below, and I'll also link to another code example ([`BundledSearchEnginesStorage`](https://searchfox.org/mozilla-mobile/source/firefox-android/android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorage.kt)) that reads from streams which may be a helpful reference.

2023-11-05 14:22 UTC, jonalmeida commented on fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FontParser.kt
> +class FontParser(inputStream: InputStream) {
Consideration: It seems like this constructor is only used for testing, so let's replace the secondary one with this, and create a method to open and set the stream that is internal and visible for testing only?

2023-11-05 14:22 UTC, jonalmeida commented on fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FontParser.kt
> +class FontParser(inputStream: InputStream) {
In Kotlin, you don't need to do these java-style bindings, you can make properties through constructors.

```suggestion
class FontParser(private val inputStream: InputStream) {
```

Based on the comment above, you can re-work this to be more concise.

2023-11-06 13:54 UTC, tomrittervg commented on fenix/app/src/androidTest/java/org/mozilla/fenix/components/FontParserTest.kt
> +    @Suppress("MaxLineLength")
It's caused by all the long string literals which don't reformat nicely; but I can break them into multi-line string concats to resolve it.

2023-11-06 14:21 UTC, jonalmeida commented on fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FontParser.kt
> +        this.inputStream.reset()
Oops, it's because of the previous function that calculates the hash of the file.

2023-11-06 14:23 UTC, jonalmeida commented on fenix/app/src/androidTest/java/org/mozilla/fenix/components/FontParserTest.kt
> +    @Suppress("MaxLineLength")
I think it's fine, but there are some other lines that this is suppressing too.

2023-11-06 19:08 UTC, jonalmeida commented on fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FontsEnumerator.kt
> +        }
They are fine in a separate file maybe? They seem unrelated to the worker class imo, but this is just styling feedback; optional.

2023-11-06 21:35 UTC, tomrittervg commented
It's complaining about the multi-line comments, but this is the formatting I get when I Save/do any of the 'Reformat Code/Reformat File/Auto-indent Lines'....

> /builds/worker/checkouts/vcs/fenix/app/src/androidTest/java/org/mozilla/fenix/components/FontParserTest.kt:17:1: Unexpected indentation (20) (should be 16) (standard:indent)

2023-11-15 20:52 UTC, jonalmeida commented
> It's complaining about the multi-line strings and hanging indentation, but this is the formatting I get when I Save/do any of the 'Reformat Code/Reformat File/Auto-indent Lines'....
> 
> > /builds/worker/checkouts/vcs/fenix/app/src/androidTest/java/org/mozilla/fenix/components/FontParserTest.kt:17:1: Unexpected indentation (20) (should be 16) (standard:indent)

I'm not sure how your IDE was setup, but maybe there is a missconfiguration somewhere because I do not have this happening for me with your patch locally. Try installing the [ktlint](https://plugins.jetbrains.com/plugin/15057-ktlint-unofficial-) and [detekt](https://plugins.jetbrains.com/plugin/10761-detekt) plugins to see if that makes Android Studio use those linter plugins to correct the auto-formatting. I have also filed BZ-1864954 to improve our documentation because it seems something is missing between our two setups.

2023-11-15 20:53 UTC, jonalmeida requested changes
Just some smaller suggestions left. Thanks!

2023-11-15 20:53 UTC, jonalmeida commented on fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontParser.kt
> +    val path: String = ""
This will always be an empty string. That doesn't seem right.

2023-11-15 20:54 UTC, jonalmeida commented on fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FontParser.kt
> +        readFontFile()
Yeah, I think that's fine. :)

2023-11-20 22:42 UTC, jonalmeida commented
> I've also [asked on the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1858193#c4), if we need to update the data review since we are changing it's sensitivity (even though it's for technical reasons).

With the response on [the bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1858193#c5), I think we are good to land this! Thanks for being patient with the review!

2023-11-20 22:43 UTC, jonalmeida commented
bors try

2023-11-20 23:06 UTC, merged