Bug 1858528 - Add rakuten and yahoo-jp-auctions search engines
mozilla-mobile/firefox-android pull request #4467
Opened 2023-11-14 01:41 UTC by sarah541

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2023-11-14 01:50 UTC, sarah541 commented
@Standard8 I added these search engines based on desktop search extensions as mentioned for these two search engines i.e [rakuten](https://searchfox.org/mozilla-central/source/browser/components/search/extensions/rakuten/manifest.json) and [yahoo-jp-auctions](https://searchfox.org/mozilla-central/source/browser/components/search/extensions/yahoo-jp-auctions/manifest.json). I converted the favicon.ico for both engines to base64-encoded PNG image and added it to the xml.

2023-11-14 20:23 UTC, rocketsroger approved these changes
🚢 Thanks!

2023-11-15 12:34 UTC, Standard8 requested changes
Thank you, this looks good, just a couple of minor corrections before we're ready to land.

2023-11-15 15:21 UTC, sarah541 commented on android-components/components/feature/search/src/main/assets/searchplugins/rakuten.xml
> +        <Param name="v" value="2" />
Eagle eye! Thank you Mark

2023-11-15 15:21 UTC, sarah541 commented on android-components/components/feature/search/src/main/assets/searchplugins/rakuten.xml
> +    <InputEncoding>utf-8</InputEncoding>
That's fair! I have updated the Pr with both comments

2023-11-15 15:23 UTC, Standard8 approved these changes
Thank you for the updates.

2023-11-16 16:58 UTC, merged