Bug 1872184 - Rate limit auth recovery checks
mozilla-mobile/firefox-android pull request #4965
Opened 2023-12-27 21:12 UTC by bendk

Don't schedule multiple auth recovery checks when they happen in the same time period.  If multiple operations run at once when the user has a bad token, then we shouldn't queue up multiple checks at the same time.

The exception to this is syncing.  When we're syncing and hit an auth error, we always want to schedule an auth recovery check so that either the sync restarts or the user enters the authentication problems state. Also, there should only be one sync scheduled at once, so there's less chance of multiple recovery checks being queued at once.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2023-12-29 10:00 UTC, Mukuljangir372 approved these changes

2024-01-24 18:14 UTC, mavduevskiy requested changes
looking good! a small nit about the comment, and we probably should write a test for checking `forSync` / `!forSync` cases

2024-01-24 18:14 UTC, mavduevskiy commented on android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/GlobalAccountManager.kt
> -            // Error within the reset time window, increment the count.
I would suggesting keeping the original comment above the increment line, but adding a single comment above the sync check explaining the case when we want to quit the execution. One more thing, a code comment is better when it's a high level description. Mentioning implementation details like `If this is for an operation wrapped by `handleFxaExceptions`, then quit` might make a comment obsolete when somebody decided to change the name of the function or refactor the general flow of execution.

2024-03-01 21:26 UTC, mavduevskiy approved these changes
looks good, 🚢it

2024-03-01 23:19 UTC, merged