Bug 1874771 - Only run 'github-push' Taskcluster tasks against main a…
mozilla-mobile/firefox-android pull request #5177
Opened 2024-01-15 21:07 UTC by ahal

…nd release branches

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2024-01-16 09:32 UTC, jcristau requested changes
This will prevent merging PRs created by github actions.

2024-01-16 15:53 UTC, ahal commented
> This will prevent merging PRs created by github actions.

How so? If a PR is created, then that PR will still get a `github-pull-request` graph. Currently those PRs are getting both `github-push` and `github-pull-request` graphs, and there's a race condition over which task ends up getting displayed in the Github checks UI (the later task overwrites the earlier task in the UI)

2024-01-16 15:55 UTC, ahal commented
Ftr, I'm not opposed to leaving tasks on as level 1.. but in my experience with VPN, if your workflow involves creating pull-requests off of branches in the canonical repo, you probably want to disable `on-push` tasks in those branches

2024-01-16 16:06 UTC, jcristau commented
> > This will prevent merging PRs created by github actions.
> 
> How so? If a PR is created, then that PR will still get a `github-pull-request` graph. Currently those PRs are getting both `github-push` and `github-pull-request` graphs, and there's a race condition over which task ends up getting displayed in the Github checks UI (the later task overwrites the earlier task in the UI)

I'll try to break down the different cases:
- for PRs created by collaborators, the pull-request graph is just fine.  We can get rid of any push graph here. (IMO they should push to a fork instead of the main repo, but that is not actually enforced)
- PRs created by humans that aren't collaborators are necessarily coming off of a fork.  They don't run ui-tests, they don't get a push graph.  No change there from this patch.
- PRs created by github actions is where we need to be careful.  These are on a branch on the main repo.  Their PR graph is incomplete, because it's not authored by a collaborator. We currently rely on the push graph in this case to satisfy merge conditions.  So we do need to keep that graph running here, that's why I suggested on the bug to add those branch name patterns both to the .tc.yml filter and to branch protections, although I'm not sure if we can say "github actions can push here but not human users".

2024-01-16 19:01 UTC, ahal commented
Ah ok, thanks for the explanation. And I missed your comment on the bug. I just replied over there.

2024-01-22 18:31 UTC, hneiva approved these changes

2024-01-22 18:31 UTC, hneiva commented on .taskcluster.yml
> +                      || (tasks_for == "github-push" && (short_head_ref == "main" || short_head_ref[:9] == "releases_"))
I'm assuming "releases_*" branches are protected in this repo?

2024-01-22 19:01 UTC, hneiva requested changes
I'll leave as requested changes according to previous conversation

2024-03-08 18:53 UTC, closed without merging