Bug 1862738 - Put credential management strings before translation
mozilla-mobile/firefox-android pull request #5225
Opened 2024-01-19 23:04 UTC by sarah541

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2024-01-19 23:21 UTC, rocketsroger approved these changes

2024-01-20 00:28 UTC, Delphine requested changes
Mostly seems like comment updates are needed (seems like many were copied directly from the previous existing string). When used, localization comments should describe the purpose and function of the immediate string they are attached to.
More about localization comments [here](https://mozilla-l10n.github.io/documentation/localization/dev_best_practices.html#add-localization-notes).

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Preference option for adding a login -->
Nit: comment should say "for adding a password"

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Preference for syncing saved logins in Fenix -->
Nit: comment should say passwords and not logins here

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Preference for syncing saved logins in Fenix, when not signed in-->
Nit: should say passwords vs logins

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Preference to access list of saved logins -->
Nit: again comment should say passwords here

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Preference to access list of saved logins -->
Comment does not address string below (it's about sync, not accessing list of saved logins)

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Empty description of list of login exceptions that we never save logins for. Parameter will be replaced by app name. -->
Nit: comment says "logins" but string is about passwords

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <string name="preferences_passwords_exceptions_description_empty_2" tools:ignore="UnusedResources">%s won\'t save passwords for sites listed here.</string>
Again, you can just drop `\ `and directly use typographic quote here

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <string name="preferences_passwords_exceptions_description_2" tools:ignore="UnusedResources">%s won\'t save passwords for these sites.</string>
same about apostrophe

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Description of list of login exceptions that we never save logins for. Parameter will be replaced by app name. -->
Nit: I think this should be about passwords too here, vs logins

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Hint for search box in logins list -->
Nit: should be "passwords" and not logins

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Message displayed in biometric prompt displayed for authentication before allowing users to view their logins -->
again should be passwords

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!-- Content description (not visible, for screen readers etc.): Sort saved logins dropdown menu chevron icon -->
This comment reads as a developer comment: "Sort saved logins dropdown menu chevron icon"
Localizers may not be familiar with technical jargon, so it's helpful to provide clear and straightforward comments that make it easy for them to understand the purpose and function of the string. I would drop that part out of the comment and just leave the first part

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!--  The saved login options menu description. -->
Nit: should be 'password' in comment

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!--  The editable text field for a login's web address. -->
comment also needs update

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!--  The editable text field for a login's username. -->
again needs update

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!--  The page title for editing a saved login. -->
comment needs update

2024-01-20 00:28 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <!--  The page title for adding new login. -->
comment needs update

2024-01-20 01:06 UTC, Delphine requested changes
Updates looking good thanks! just spotted one more update during this review

2024-01-20 01:06 UTC, Delphine commented on fenix/app/src/main/res/values/strings.xml
> +    <string name="preferences_passwords_saved_logins_description_empty_learn_more_link_2" tools:ignore="UnusedResources">Learn more about sync</string>
I missed this! "Sync" should have a capital "S" (see for example string above)

2024-01-20 01:11 UTC, Delphine approved these changes
Thanks for the fixes!

2024-01-20 01:43 UTC, merged