TestSetup helper batch 1
mozilla-mobile/firefox-android pull request #5299
Opened 2024-01-25 15:05 UTC by sv-ohorvath

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2024-02-06 13:02 UTC, AndiAJ approved these changes
👍🏽

2024-02-07 06:13 UTC, jjSDET requested changes

2024-02-07 06:13 UTC, jjSDET commented on fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
> +            bookmarks?.forEach { bookmarksStorage.deleteNode(it.guid) }
try using a `suspend coroutine` here, and let's see if this fixes it. it _should_ only continue after we get confirmation the `delete` instruction as been commited and applied to the data store. 🤞 

```
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlin.coroutines.suspendCoroutine

private suspend fun deleteBookmark(guid: String) {
        suspendCoroutine<Unit> { continuation ->
            bookmarksStorage.deleteNode(guid) { success ->
                if (success) {
                    continuation.resume(Unit)
                } else {
                    continuation.resumeWithException(Exception("Failed to delete bookmark with GUID $guid"))
                }
            }
        }
    }
```

2024-02-07 15:10 UTC, jjSDET approved these changes
We'll keep looking into finding some good ways to verify the db status, but for now, this looks good. 

We can hack more on this later this week and get something in place early next week.

2024-02-07 17:14 UTC, merged

2024-02-07 19:38 UTC, AaronMT commented
Reverting as this breaks `ui-test-apk-legacy` tests on 26-29 due to missing methods in some of the Android calls. If you'd like to test that Task on a PR, [modify this line](https://github.com/mozilla-mobile/firefox-android/blob/b6efccdd0df0d50c391b2b5671f776665c24e8e0/taskcluster/ci/ui-test-apk/kind.yml#L410) to `github-pull-request`