Bug 1880176 - Clean up some AndroidX dependency management
mozilla-mobile/firefox-android pull request #5589
Opened 2024-02-13 22:48 UTC by rvandermeulen

### GitHub Automation

Used by GitHub Actions.

2024-02-13 22:59 UTC, Amejia481 approved these changes
LGTM!

2024-02-13 23:57 UTC, gabrielluong commented on android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
> +        const val datastore="1.0.0"
```suggestion
        const val datastore = "1.0.0"
```

2024-02-14 00:04 UTC, gabrielluong commented on fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
> -    const val androidx_datastore = "androidx.datastore:datastore:${FenixVersions.androidx_datastore}"
We're doing something very subtle here, which is that we are moving some of these Fenix only dependencies over to the DependenciesPlugin which only should contain the AC dependencies. I don't believe we want our A-C dependencies to know about any dependencies other than the ones it needs to maintain the AC is its own independent library.

2024-02-14 00:11 UTC, gabrielluong commented on fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
> -    const val androidx_datastore = "androidx.datastore:datastore:${FenixVersions.androidx_datastore}"
I think we should absolutely avoid moving one-off dependencies into the AC DependenciesPlugin and instead we should make FenixDependenciesPlugin dependent on DependenciesPlugin and reuse the `Version.androidx_datastore`

2024-02-14 00:23 UTC, gabrielluong requested changes
Let's avoid centralizing dependencies into the AC DependenciesPlugin

2024-02-20 20:06 UTC, rvandermeulen commented
I can't get the inheritance to work and am not interested in trying to figure it out. We'll just switch to version catalogs post-migration and drop the plugins entirely.

2024-02-20 20:07 UTC, closed without merging