Bug 1812251 - making the URL icons from the Bookmarks page larger
mozilla-mobile/firefox-android pull request #883
Opened 2023-02-18 13:16 UTC by gitstart

### What
The PR makes the URL icons from the Bookmarks page larger

### Steps to test

1. Have Google Accessibility Scanner installed.
2. Save some bookmarks.
3. Open "Bookmarks" from the three-dot menu.
4. Using the Accessibility Scanner, scan the "Bookmarks" page.

### Screenshots
| Issue | Fix |
| ----- | --- |
| ![URLicon](https://user-images.githubusercontent.com/2725300/216988098-a5a41bd5-6d38-4799-9d1d-7ddd7b02ea96.png) | ![66 Fix](https://user-images.githubusercontent.com/2725300/217162540-0a4e8284-2d58-4963-8ba8-2a504ebce69e.png) |

### Pull Request checklist
 - [ ] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.
### GitHub Automation

2023-02-20 06:56 UTC, Mugurell requested changes

2023-02-20 06:56 UTC, Mugurell commented on fenix/app/src/main/res/values/dimens.xml
> +    <dimen name="history_favicon_width_height">48dp</dimen>
If the problem relates to accessibility not to how the UI looks then we should avoid changing the UI and only update the accessibility support.
The touch target can be made bigger by using the [increaseTapArea](https://searchfox.org/mozilla-mobile/rev/2d9dd7b862d87ac539a52b9b0d99160b61745dae/firefox-android/fenix/app/src/main/java/org/mozilla/fenix/ext/View.kt#22-31) method. Example: https://github.com/mozilla-mobile/firefox-android/blob/a05ece3df1f60e7b10ab4b564b82f47b7ba8d0eb/fenix/app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt#L47

2023-02-21 16:01 UTC, gitstart commented
Thank you @Mugurell for reviewing🙏.
Will soon push the requested changes. 🚀

2023-02-21 16:33 UTC, gitstart commented
The remaining accessibility issues includes a `Text scaling` issue on the toolbar which will require changing the toolbar UI for the whole app. The second issue is an `Item description` issue on the menu overflow button, because the screen can have multiple overflow buttons which have the same `content description` which will not affect the user as they are on different items.

2023-02-21 16:34 UTC, gitstart commented
Hello @Mugurell,
Requested Changes Pushed. 🚀
Thank you 🙏

2023-03-09 13:11 UTC, Mugurell requested changes
Thank you for the updates!
There two small things to take care of and then we can look into landing this.

2023-03-09 13:11 UTC, Mugurell commented on fenix/app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt
> +        overflowView.increaseTapArea(OVERFLOW_EXTRA_DIPS)
The accessibility issues with this button was resolved on all library screens by https://github.com/mozilla-mobile/firefox-android/pull/1122 which added the padding needed to have the button bigger but visually appear the same.
So this line won't be needed.

2023-03-09 13:11 UTC, Mugurell commented on fenix/app/src/main/java/org/mozilla/fenix/library/LibrarySiteItemView.kt
> +        private const val OVERFLOW_EXTRA_DIPS = 16
I see this View already having 40dp height/width - [the favicon](https://searchfox.org/mozilla-mobile/rev/2539bc45c927cd8ec585928216685141b6e7ec25/firefox-android/fenix/app/src/main/res/layout/library_site_item.xml#14-29) uses [history_favicon_width_height](https://searchfox.org/mozilla-mobile/rev/2539bc45c927cd8ec585928216685141b6e7ec25/firefox-android/fenix/app/src/main/res/values/dimens.xml#16).
So we'd only need to increase the tap area with (48 - 40) / 2 => 4dp.
(Want to also note again that we need this only for the favicon, not for the overflow icon)

2023-03-20 05:20 UTC, gitstart commented
Hello @Mugurell,
Requested changes are pushed. 🙏

2023-09-04 17:28 UTC, titooan commented
Thanks for your contribution! It looks like this bug has already been fixed by PR #862, so I'll go ahead and close this. 
Happy to accept more patches in the future!

2023-09-04 17:29 UTC, titooan commented
Thanks for your contribution! It looks like this bug has already been fixed by PR #862, so I'll go ahead and close this.
Happy to accept more patches in the future!

2023-09-04 17:29 UTC, closed without merging