Bug 1809815 - Talkback does not mention `Show all` as a button in the Recently visited section
mozilla-mobile/firefox-android pull request #900
Opened 2023-02-20 08:04 UTC by gitstart

### What
Talkback does not mention "Show all" as a button in the Recently visited section

### Screenshots
### Issue video
https://www.loom.com/share/78849456150c422cb6958b1f69ae0582

### Demo video after fix
https://www.loom.com/share/7470a8dd1f8c48dc89d44c9dff19819d

### Pull Request checklist
 - [ ] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1809815

2023-02-20 10:14 UTC, Mugurell requested changes

2023-02-20 10:14 UTC, Mugurell commented on fenix/app/src/main/res/values-en-rGB/strings.xml
> +    <string name="past_explorations_show_all_content_description_2">Show all past explorations button</string>
Saw that we already have another similar [Show all recent tabs button](https://searchfox.org/mozilla-mobile/rev/2d9dd7b862d87ac539a52b9b0d99160b61745dae/firefox-android/fenix/app/src/main/res/values/strings.xml#138) string but this is not the direction we want to go.
We could look into adding `Role.Button` to the currently used [ClickableText](https://searchfox.org/mozilla-mobile/rev/2d9dd7b862d87ac539a52b9b0d99160b61745dae/firefox-android/fenix/app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt#110-112) or we could maybe refactor the `ClickableText` to a `TextButton` with this ensuring that the expected role is set and read by a11y services.

2023-02-21 15:59 UTC, gitstart commented
Thank you @Mugurell for reviewing🙏.
Will soon push requested changes. 🚀

2023-03-03 10:21 UTC, Mugurell reviewed
Thank you for the update!
Just one small change to ensure the project code style is followed and we can land this.

2023-03-03 10:21 UTC, Mugurell commented on fenix/app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
> +                        },
Even with using named parameters we try to respect the declaration order for method parameters.
For `Text` the `modifier` should be above `style`, the same as in the current code.

2023-03-03 10:21 UTC, Mugurell commented
bors try

2023-03-10 15:43 UTC, Mugurell approved these changes
Thank you!
LGTM.
To be landed after the code freeze.

2023-03-16 00:54 UTC, rvandermeulen commented
@Mugurell Is this good to land now?

2023-03-16 14:11 UTC, merged