Bug 1815633 - Set margin top to zero when address bar is set to not to hide on scroll which removes a blank space on installed pwa
mozilla-mobile/firefox-android pull request #914
Opened 2023-02-20 12:55 UTC by gitstart

The PR fixes a blank space on installed PWA when the address bar is set not to hide on scroll.

### Fix description
Remove the margin-top

### Screenshots
| Issue | Fix |
| -----  | ----- |
| ![image](https://user-images.githubusercontent.com/2725300/213976692-e1de6267-c1d1-46fc-9b51-c189e5bcd07e.png) |  ![Screenshot_20230123-122243](https://user-images.githubusercontent.com/2725300/214016903-a3e36cfa-101f-4531-9ad8-f19c05043bb5.png) |

### Pull Request checklist
 - [ ] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.
### GitHub Automation

2023-02-20 13:23 UTC, Mugurell commented on fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
> +                swipeRefreshParams.topMargin = 0
This seems to cause issues in normal browsing:

![image](https://user-images.githubusercontent.com/11428869/220120364-a6b1e321-8ae2-4dc5-8c29-a8815581d328.png)

Seems like we need to differentiate between the different scenarios and pass the right `toolbarHeight` value to `initializeEngineView` which would directly set it.

2023-02-20 13:23 UTC, Mugurell requested changes
Looks like there's a bit more investigation needed here.

2023-02-20 19:14 UTC, gitstart commented
Thank you @Mugurell for reviewing. 🙏

2023-02-28 08:08 UTC, gitstart commented
Hello @Mugurell,
Requested changes are pushed. 🚀

2023-03-02 06:28 UTC, gitstart commented
> > Hello @Mugurell, Requested changes are pushed. 🚀
> 
> Seems like the current patch is exactly the initial one which can break other scenarios as discussed here - [#914 (comment)](https://github.com/mozilla-mobile/firefox-android/pull/914#discussion_r1111956080) ?

Hello @Mugurell,
Changes regarding the current patch is pushed with new approach. 
Hope this will not bring any new issue or break.🙏

2023-07-21 14:33 UTC, t-p-white commented
@gitstart Thank you for creating this patch, the work is really appreciated. While reviewing your PR I've found that this bug is actually already fixed in the current Fenix Beta version 116, therefore this patch will no longer be needed. Thanks again for your effort on this!

2023-07-21 14:33 UTC, closed without merging

2023-08-05 03:46 UTC, rhendric commented
As reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1847106, this bug isn't actually fixed in 116 (at least on my device). Can this patch be considered again? It looks quite tractable.