Bug 1810629 - Add an Android shortcut to go straight to the login and passwords page
mozilla-mobile/firefox-android pull request #915
Opened 2023-02-20 13:08 UTC by gitstart

The PR creates a shortcut that users can place on the HomeScreen and when the user clicks the shortcut it will open the `login and passwords page`

### Issue Screenshots
No video this is a new feature not bug

### Fix Screenshots
https://www.loom.com/share/ed2452528b754822afee436b3dca64f8

### Pull Request checklist
 - [ ] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.
### GitHub Automation

2023-02-28 16:59 UTC, gabrielluong commented
Since the original issue was a feature request, we would need Product to weigh in on this. cc @kbrosnan

2023-03-01 08:47 UTC, gitstart commented
> Since the original issue was a feature request, we would need Product to weigh in on this. cc @kbrosnan

Okay @gabrielluong. 🙏
Will wait for the response.

2023-03-09 22:13 UTC, amedyne commented
Based on a review today: 
Product decision: This is a useful feature, so we are okay taking in the change.
UX: We need to confirm with Content/Design about the String and menu Lock Icon. FYI @lime124 and @ewachowiak

2023-03-13 13:53 UTC, ewachowiak commented
To confirm, the feature works like this:
- User long presses the app icon on Home screen
- User selects "Password manager"
- A shortcut called "Password manager" appears on the Home screen

Once confirmed, I'm going to check with Katie Lower on the strings (she's working on the password feature right now)

2023-03-14 08:28 UTC, gitstart commented
> To confirm, the feature works like this:
> 
> * User long presses the app icon on Home screen
> * User selects "Password manager"
> * A shortcut called "Password manager" appears on the Home screen
> 
> Once confirmed, I'm going to check with Katie Lower on the strings (she's working on the password feature right now)

Yes confirmed @ewachowiak

2023-03-14 13:48 UTC, ewachowiak commented
Thanks for confirming. The label "Password manager" makes it sound like it will take you to the password manager, not that it will add a shortcut. I suggest changing the text to "Password manager shortcut". I think a bigger issue might be that the feature is not called "password manager" inside Firefox. Let me check with Katie and get back to you. Thanks for your patience.
.

2023-03-14 15:24 UTC, ewachowiak commented
Update: I spoke to Katie and confirmed that the long-term plan is to change the name from "Logins and passwords" to just "Passwords." In light of this and of the space restrictions we have here, here is my string recommendation: 
`Passwords shortcut`

2023-03-15 06:26 UTC, gitstart commented
> Update: I spoke to Katie and confirmed that the long-term plan is to change the name from "Logins and passwords" to just "Passwords." In light of this and of the space restrictions we have here, here is my string recommendation: `Passwords shortcut`

Thank you @ewachowiak, 
We will make the changes and push shortly.

2023-03-20 17:59 UTC, cwzilla commented
Hi, design systems team here. Please see the attachment for the lock icon. Thanks!
![lock-24](https://user-images.githubusercontent.com/87655586/226426823-1ee73958-52c9-4884-92b0-6faffc97758a.svg)

2023-03-23 20:45 UTC, amedyne commented
@gitstart please update with the latest icon from @cwzilla .

2023-03-24 06:00 UTC, gitstart commented
> @gitstart please update with the latest icon from @cwzilla .

Hello @amedyne,
Thank you for sharing the icon. We had pushed all the changes.
Please take a look.✔
Thank you.🙌

2023-05-03 21:43 UTC, rocketsroger reviewed
Great change.  Looks good.  One small issue.
I did ran into some issue starting Fenix until I rebase your changes to main.  Please rebase to main and I'll retry to confirm there's no issue.  Thanks

2023-05-03 21:43 UTC, rocketsroger commented on fenix/app/src/main/java/org/mozilla/fenix/home/intent/OpenPasswordManagerIntentProcessor.kt
> +            MetricsUtils.Source.SHORTCUT
This line is not needed?

2023-05-03 23:35 UTC, zmckenney requested changes

2023-05-03 23:35 UTC, zmckenney commented on fenix/app/src/nightly/res/xml/shortcuts.xml
> +        android:icon="@drawable/ic_static_shortcut_password_manager"
Same issue here. This should be `android:icon="@drawable/ic_static_password_shortcut"`

2023-05-03 23:35 UTC, zmckenney commented on fenix/app/src/release/res/xml/shortcuts.xml
> +        android:icon="@drawable/ic_static_shortcut_password_manager"
Same issue here. This should be `android:icon="@drawable/ic_static_password_shortcut"`

2023-05-03 23:35 UTC, zmckenney commented on fenix/app/src/beta/res/xml/shortcuts.xml
> +        android:icon="@drawable/ic_static_shortcut_password_manager"
This path is incorrect. This should be `android:icon="@drawable/ic_static_password_shortcut"`

2023-05-15 14:20 UTC, rocketsroger approved these changes
LGTM 🚢

2023-05-15 18:24 UTC, zmckenney approved these changes

2023-05-15 19:51 UTC, merged